name: Convert Excel to JSON

on:
  push:
    paths:
      - 'excel/*.xlsx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install xlsx

      - name: Run convert script
        run: node scripts/convert.js

      - name: Commit JSON result
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add db/
          git commit -m "auto convert excel to json" || echo "No changes"
          git push