name: build database

on:
  push:
    paths:
      - "excel/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install xlsx

    - run: node build/convert_excel.js

    - name: commit database
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add db/promo.json
        git commit -m "auto build database" || echo "no change"
        git push