name: Convert Excel to JSON

permissions:
  contents: write

on:
  push:
    paths:
      - 'excel/**'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install xlsx

      - run: node scripts/convert.js

      - name: Debug
        run: ls -R

      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          mkdir -p db

          git add db/promo.json

          git commit -m "auto convert" || echo "no changes"

          git push